version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
    - ./frontend:/app/frontend

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
